 const photos = [
{photo:"turtles.jpg",title:"Turtles"},
{photo:"spider.jpg",title:"Spider"},
{photo:"sky.jpg",title:"Sky"},
{photo:"sharks.jpg",title:"Sharks"},
{photo:"RubberDuck.JPG",title:"Rubber Duck"},
{photo:"octopus.jpg",title:"Octopus"},
{photo:"iguana.jpg",title:"Iguana"},
{photo:"flower.jpg",title:"Flower"},
{photo:"donkey.jpg",title:"Donkey"},
{photo:"dog.jpg",title:"Dog"},
{photo:"bee.jpg",title:"Bee"},
{photo:"rubikscube.jpg",title:"Rubik's Cube"},
{photo:"anseladamstree.jpg",title:"Ansel Adam's tree"},
{photo:"cow.jpg",title:"Cow"},
{photo:"phonebooth.jpg",title:"Phone Booth"},
{photo:"racecar.jpg",title:"Race Car"},
{photo:"tiger.jpg",title:"Tiger"},
{photo:"pineapples.jpg",title:"Pineapples"},
{photo:"castle.jpg",title:"Castle"},
{photo:"flamingos.jpg",title:"Flamingos"},
{photo:"owl.jpg",title:"Owl"},
{photo:"computercode.jpg",title:"Computer Code"},
{photo:"squirrel.jpg",title:"Squirrel"},
{photo:"raven.jpg",title:"Raven"},
{photo:"byplane.jpg",title:"Biplane"},
{photo:"axolotl.jpg",title:"Axolotl"},
{photo:"macaw.jpg",title:"Macaw"},
{photo:"cacti.jpg",title:"Cacti"},
{photo:"polarbear.jpg",title:"Polar Bear"},
{photo:"poisondartfrog.jpg",title:"Poison Dart Frog"},
{photo:"bellpeppers.jpg",title:"Bell Peppers"},
{photo:"pumpkins.jpg",title:"Pumpkins"},
{photo:"turniptruck.jpg",title:"Turnip Truck"},
{photo:"tools.jpg",title:"Tools"},
{photo:"jellyfish.jpg",title:"Jellyfish"},
{photo:"cocktails.jpg",title:"Cocktails"},
{photo:"strawberries.jpg",title:"Strawberries"},
{photo:"crayons.jpg",title:"Crayons"},
{photo:"gemstones.jpg",title:"Gemstones"},
{photo:"peacock.jpg",title:"Peacock"},
];

export default photos;